/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package delpino_torres_manuel_multijuego;

import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Ahorcado extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    private final int MAX_INTENTOS = 6;
    private String palabraGanadora;
    private int intentos;
    private JLabel[] resultado;
    private JLabel[] ahorcado;
    private int turno;
    private int victoriasJugador1;
    private int victoriasJugador2;
    private boolean esJuegoesmpezado;

    public Ahorcado() {
        initComponents();
        this.setTitle("Ahorcado");
        this.setLocationRelativeTo(null);
        this.palabraGanadora = "";
        this.intentos = 0;
        this.resultado = new JLabel[5];
        this.ahorcado = new JLabel[6];
        this.establecerCasillas();
        this.establecerAhorcado();
        this.reiniciarDibujo();
        this.esJuegoesmpezado = false;
        this.turno = this.randomTurno();
        jLabel16.setText(this.establecerTurno());
        this.victoriasJugador1 = 0;
        this.victoriasJugador2 = 0;
        jLabel10.setText(jLabel10.getText() + " " + this.victoriasJugador1);
        jLabel11.setText(jLabel11.getText() + " " + this.victoriasJugador2);
    }

    private String establecerTurno() {
        if (this.turno == 1) {
            return "Turno de " + jLabel8.getText();
        } else {
            return "Turno de " + jLabel9.getText();
        }

    }

    private int randomTurno() {
        Random gen = new Random();
        return gen.nextInt(2) + 1;
    }

    private void establecerCasillas() {
        this.resultado[0] = jLabel12;
        this.resultado[1] = jLabel13;
        this.resultado[2] = jLabel14;
        this.resultado[3] = jLabel15;
        this.resultado[4] = jLabel7;
    }

    private void establecerAhorcado() {
        this.ahorcado[0] = jLabel1;
        this.ahorcado[1] = jLabel2;
        this.ahorcado[2] = jLabel3;
        this.ahorcado[3] = jLabel4;
        this.ahorcado[4] = jLabel5;
        this.ahorcado[5] = jLabel6;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setToolTipText("Fallos");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setText("Introducir letra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 150, 50));
        jButton1.getAccessibleContext().setAccessibleDescription("Introducir letra");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("-");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 30, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("-");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 30, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("-");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 30, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("-");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 30, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("-");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 30, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("O");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 74, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("\\");
            jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

            jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
            jLabel3.setText("/");
            jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

            jLabel4.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
            jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel4.setText("|");
            jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 84, 60));

            jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
            jLabel5.setText("\\");
                jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 50, -1));

                jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
                jLabel6.setText("/");
                jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

                jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 390, 280));
                jPanel2.getAccessibleContext().setAccessibleDescription("Resultado");

                jLabel8.setBackground(new java.awt.Color(102, 153, 255));
                jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(255, 255, 255));
                jLabel8.setText("Jugador 1");
                jLabel8.setOpaque(true);
                jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

                jLabel9.setBackground(new java.awt.Color(255, 102, 102));
                jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel9.setForeground(new java.awt.Color(255, 255, 255));
                jLabel9.setText("Jugador 2");
                jLabel9.setOpaque(true);
                jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

                jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel10.setText("Numero de victorias:");
                jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

                jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel11.setText("Numero de victorias:");
                jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

                jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel16.setText("Turno de:");
                jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

                jTextArea1.setEditable(false);
                jTextArea1.setColumns(20);
                jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
                jTextArea1.setForeground(new java.awt.Color(255, 51, 51));
                jTextArea1.setRows(5);
                jScrollPane1.setViewportView(jTextArea1);

                jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 140, -1));

                jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delpino_torres_manuel_multijuego/3f59c051261e189b2ed9ba4bbfb904ba.gif"))); // NOI18N
                jLabel17.setOpaque(true);
                jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

                jMenu1.setText("Opciones");

                jMenu3.setText("Introducir palabra");
                jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mousePressed(java.awt.event.MouseEvent evt) {
                        jMenu3MousePressed(evt);
                    }
                });
                jMenu1.add(jMenu3);

                jMenu4.setText("Resetear juego");
                jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mousePressed(java.awt.event.MouseEvent evt) {
                        jMenu4MousePressed(evt);
                    }
                });
                jMenu1.add(jMenu4);

                jMenu5.setText("Consultar palabra");
                jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mousePressed(java.awt.event.MouseEvent evt) {
                        jMenu5MousePressed(evt);
                    }
                });
                jMenu1.add(jMenu5);

                jMenuBar1.add(jMenu1);

                jMenu6.setText("Jugadores");

                jMenu7.setText("Introducir nombre del jugador 1");
                jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mousePressed(java.awt.event.MouseEvent evt) {
                        jMenu7MousePressed(evt);
                    }
                });
                jMenu6.add(jMenu7);

                jMenu8.setText("Introducir nombre del jugador 2");
                jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mousePressed(java.awt.event.MouseEvent evt) {
                        jMenu8MousePressed(evt);
                    }
                });
                jMenu6.add(jMenu8);

                jMenuBar1.add(jMenu6);

                jMenu2.setText("Salir");
                jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mousePressed(java.awt.event.MouseEvent evt) {
                        jMenu2MousePressed(evt);
                    }
                });
                jMenuBar1.add(jMenu2);

                setJMenuBar(jMenuBar1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                jPanel1.getAccessibleContext().setAccessibleDescription("Panel");

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!this.palabraGanadora.equalsIgnoreCase("")) {
            this.esJuegoesmpezado = true;
            if (this.intentos < this.ahorcado.length) {
                boolean acierto = false;
                String letra = JOptionPane.showInputDialog(this, "Introduzca una letra");

                while (letra.length() > 1 || !Ahorcado.validarNumeros(letra)) {
                    if (letra.length() > 1) {
                        JOptionPane.showMessageDialog(this, "No puede introducir mas de una letra", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "No puede introducir numeros o simbolos", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    letra = JOptionPane.showInputDialog(this, "Introduzca solo una letra");
                }
                for (int i = 0; i < this.palabraGanadora.length(); i++) {
                    String letraGanadora = this.palabraGanadora.substring(i, i + 1);

                    if (letraGanadora.equalsIgnoreCase(letra)) {
                        resultado[i].setText(letra);
                        acierto = true;
                        if (this.continuarJugando() == -1) {
                            JOptionPane.showMessageDialog(this, "Enhorabuena " + this.nombreGanador() + " has ganado");
                            this.reiniciarJuego();
                            this.esJuegoesmpezado = false;
                        }
                    }
                }
                if (!acierto) {
                    jTextArea1.setText(jTextArea1.getText() + " " + this.intentos + " - " + letra + "\n");
                    this.intentos++;
                    if (this.intentos < this.ahorcado.length) {
                        this.ahorcado[this.intentos - 1].setVisible(true);
                        JOptionPane.showMessageDialog(this, "Has fallado te quedan " + (MAX_INTENTOS - this.intentos) + " intentos.");
                    } else {
                        this.ahorcado[this.intentos - 1].setVisible(true);
                        JOptionPane.showMessageDialog(this, "Has perdido!!,la palabra era " + this.palabraGanadora + " es turno de " + this.nombreCambioJugador());
                        this.reiniciarJuego();
                    }

                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Para comenzar a jugar introduzca una palabra");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private String nombreCambioJugador() {
        if (this.turno == 1) {
            this.turno = 2;
            return jLabel9.getText();
        } else {
            this.turno = 1;
            return jLabel8.getText();
        }

    }

    private String nombreGanador() {
        if (this.turno == 1) {
            this.turno = 2;
            this.victoriasJugador1++;
            jLabel10.setText("Numero de victorias: " + this.victoriasJugador1);
            jLabel16.setText(this.establecerTurno());
            return jLabel8.getText();
        } else {
            this.turno = 1;
            this.victoriasJugador2++;
            jLabel11.setText("Numero de victorias: " + this.victoriasJugador2);
            jLabel16.setText(this.establecerTurno());
            return jLabel9.getText();
        }

    }

    /*con este metodo estatico validadmos si se han introducido solo numero
 el * nos permite establece que van a ser todos los valores que queramos
 si pusieramos {1,5}, nos controlaria tambien la cantidad que introducimos
     */
    public static boolean validarNumeros(String datos) {
        return datos.matches("[a-zA-Z]*");
    }

    private void jMenu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MousePressed
        // TODO add your handling code here:
        if (this.palabraGanadora.equalsIgnoreCase("")) {
            this.palabraGanadora = JOptionPane.showInputDialog("Introduzca una palabra de 5 letras.");

            if (this.palabraGanadora == null) {
                this.palabraGanadora = "";
            }

            while (this.palabraGanadora.length() != 5 || this.palabraGanadora.equalsIgnoreCase("") || !Ahorcado.validarNumeros(palabraGanadora)) {
                if (this.palabraGanadora.equalsIgnoreCase("")) {
                     JOptionPane.showMessageDialog(this, "Debe introducir una palabra para comenzar a jugar.", "Error", JOptionPane.ERROR_MESSAGE);
                    this.palabraGanadora = "";
                } else if (!Ahorcado.validarNumeros(this.palabraGanadora)) {
                    JOptionPane.showMessageDialog(this, "La palabra no puede contener simbolos ni numeros", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "La palabra introducida debe tener 5 letras", "Error", JOptionPane.ERROR_MESSAGE);
                }
                this.palabraGanadora = JOptionPane.showInputDialog("Introduzca una palabra de 5 letras.");

                if (this.palabraGanadora == null) {
                    this.palabraGanadora = "";
                }
            }
            this.esJuegoesmpezado = true;
        } else {
            JOptionPane.showMessageDialog(this, "Ya hay una palabra introducida debe reiniciar.");
        }
    }//GEN-LAST:event_jMenu3MousePressed

    private void jMenu4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MousePressed
        // TODO add your handling code here:
        this.resetearJuego();
    }//GEN-LAST:event_jMenu4MousePressed

    private void resetearJuego() {
        this.reiniciarJuego();
        this.victoriasJugador1 = 0;
        this.victoriasJugador2 = 0;
        jLabel11.setText("Numero de victorias: " + this.victoriasJugador2);
        jLabel10.setText("Numero de victorias: " + this.victoriasJugador1);
        jLabel8.setText("Jugador 1");
        jLabel9.setText("Jugador 2");
        this.turno = this.randomTurno();
        jLabel16.setText(this.establecerTurno());
        this.esJuegoesmpezado = false;
        JOptionPane.showMessageDialog(this, "Juego reseteado.");
    }


    private void jMenu5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MousePressed
        // TODO add your handling code here:
        if (this.palabraGanadora.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Todavia no se ha elegido una palabra");
        } else {
            JOptionPane.showMessageDialog(this, "La palabra es: " + this.palabraGanadora);
        }

    }//GEN-LAST:event_jMenu5MousePressed

    private void jMenu7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MousePressed
        // TODO add your handling code here:
        jLabel8.setText(JOptionPane.showInputDialog("Introduzca el nombre del jugador 1: "));
        jLabel16.setText(this.establecerTurno());
    }//GEN-LAST:event_jMenu7MousePressed

    private void jMenu8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MousePressed
        // TODO add your handling code here:
        jLabel9.setText(JOptionPane.showInputDialog("Introduzca el nombre del jugador 2: "));
        jLabel16.setText(this.establecerTurno());
    }//GEN-LAST:event_jMenu8MousePressed

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
        // TODO add your handling code here:
        Object[] opcion = {"Si", "No"};
        int respuesta = JOptionPane.showOptionDialog(this, "¿Desea cerrar el ahorcado?", "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcion, opcion[1]);
        if (respuesta == 0) {
            Menu nuevo = new Menu();
            nuevo.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenu2MousePressed
    //si se devuelve -1 se para el juego
    private int continuarJugando() {
        int pos = -1;
        int i = 0;
        while (i < this.resultado.length && this.resultado[i].getText() != "-") {
            i++;
        }

        if (i < this.resultado.length) {
            pos = i;
        }

        return pos;
    }

    private void reiniciarJuego() {
        this.reiniciarDibujo();
        this.reiniciarCasillas();
        this.intentos = 0;
        this.palabraGanadora = "";
        this.jTextArea1.setText("");
    }

    private void reiniciarCasillas() {
        for (int i = 0; i < this.resultado.length; i++) {
            this.resultado[i].setText("-");
        }

    }

    private void reiniciarDibujo() {
        for (int i = 0; i < this.ahorcado.length; i++) {
            this.ahorcado[i].setVisible(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
